table Payment
	lineageTag: 11c458d7-ad45-46d6-a4e5-5d334e9be454

	column order_id
		dataType: string
		lineageTag: 533872ee-69ba-4db1-b3f5-8d690d6c5d03
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: int64
		formatString: 0
		lineageTag: a3ca5b38-639c-4ee9-bc85-d6ab6435251d
		summarizeBy: sum
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: d56f3ac9-ceec-4d1c-84b9-b9dd841e0a60
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 5bb6d87c-3e87-418e-8274-9f9baa8a42c3
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: 91de1290-538b-43e1-9b64-393f9552ab10
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Payment = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ghale\Documents\DataSets\olist_order_payments_dataset.csv\olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"payment_sequential", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type number}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"order_id", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

