table Product
	lineageTag: 5fdcb987-a74a-431d-af16-152a192a738e

	column product_id
		dataType: string
		lineageTag: 9b487013-0935-4be4-b5a4-2f05f248095f
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: cfb96095-84c1-43a5-aea1-19d0b9d22751
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(olist_products_dataset, {"product_category_name"}, product_category_name_translation, {"product_category_name"}, "product_category_name_translation", JoinKind.LeftOuter),
				    #"Expanded product_category_name_translation" = Table.ExpandTableColumn(Source, "product_category_name_translation", {"product_category_name_english"}, {"product_category_name_english"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded product_category_name_translation",{"product_category_name"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"product_category_name_english", "category"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

